# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: kinesis-tailf
    env:
      - CGO_ENABLED=0
    main: ./cmd/kinesis-tailf/main.go
    binary: kinesis-tailf
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
  - id: kinesis-cat
    env:
      - CGO_ENABLED=0
    main: ./cmd/kinesis-cat/main.go
    binary: kinesis-cat
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
